# Generated by Django 3.2 on 2021-04-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
