# Generated by Django 3.2 on 2021-04-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_create_date_blogcomment_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
